# Generated by Django 4.1.7 on 2023-03-08 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagesapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tier_name", models.CharField(max_length=200)),
                ("thumbnail_sizes", models.CharField(max_length=200)),
                ("original_file", models.BooleanField(default=False)),
                ("generate_expiring", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.ImageField(
                        blank=True, null=True, upload_to=imagesapp.models.upload_to
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="imagesapp.accounttier",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.CharField(max_length=200, null=True)),
                (
                    "url",
                    models.ImageField(
                        blank=True, null=True, upload_to=imagesapp.models.upload_to
                    ),
                ),
                (
                    "related_image_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="imagesapp.imagemodel",
                    ),
                ),
            ],
        ),
    ]
